version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:latest
    ports:
      - 127.0.0.1:9292:9292/tcp
    networks:
      front_net:
        aliases:
          - comment_ui
          - post_ui
  post:
    build: ./post-py
    image: ${USERNAME}/post:latest
    networks:
      - front_net
      - back_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:latest
    networks:
      - front_net
      - back_net
volumes:
  post_db:

networks:
  front_net:
  back_net:
